let
    // 1. Point to your MAIN data table
    Source = GDC_load,

    // 2. Point to your REPLACEMENT table and filter out nulls
    ReplacementTableSource = geoCov,
    ReplacementTable = Table.SelectRows(ReplacementTableSource, each [YourFindColumnName] <> null),

    // --- No more changes needed below this line ---

    ReplacementList = List.Buffer(Table.ToRows(ReplacementTable)),
    ColumnsToLookIn = {"covcountry"},

    // ... The rest of your code remains the same
