let
    // 1. Point to your MAIN data table (the one with 'covcountry')
    Source = GDC_load, // <-- MAKE SURE this matches the name of your main data query

    // 2. Point to your REPLACEMENT table (your 'geoCov' table)
    ReplacementTable = geoCov, // <-- MAKE SURE this matches the name of your geoCov query

    // Convert the replacement table into a list of rows for faster processing
    ReplacementList = List.Buffer(Table.ToRows(ReplacementTable)),

    // Perform the replacements on ONLY the 'covcountry' column
    ReplaceValues = Table.TransformColumns(Source, {
        "covcountry", // <-- Specifies the exact column to change
        (cellValue) => List.Accumulate(
            ReplacementList,
            cellValue,
            (currentText, replacementPair) => Text.Replace(currentText, replacementPair{0}, replacementPair{1})
        ),
        type text
    })
in
    ReplaceValues
